# Generated by Django 6.0.2 on 2026-02-27 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_rename_created_at_ticket_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('Technical', 'Technical'), ('Billing', 'Billing'), ('General', 'General')], default='General', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='suggested_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
