# Generated by Django 6.0.2 on 2026-02-27 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_alter_ticket_category_alter_ticket_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='suggested_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
