# Generated by Django 6.0.2 on 2026-02-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_alter_ticket_suggested_response'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='suggested_response',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Hardware', 'Hardware'), ('Software', 'Software'), ('Network', 'Network')], default='General', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Closed', 'Closed')], default='Open', max_length=20),
        ),
    ]
